services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/tasktrackerscheduler?createDatabaseIfNotExist=true
      - spring.datasource.username=postgres
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.password=guest
      - spring.rabbitmq.username=guest
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  postgres:
    image: postgres:17.0
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tasktrackerscheduler
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  rabbitmq:
    image: rabbitmq:4.0.3-management
    restart: "no"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5433:5432"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  postgres_data:
  rabbitmq_data:
